# The 13 episode pages, read off the originals.
EPISODES = [{'guest': {'bio': 'Builds AI products at SAP, after an early run as an entrepreneur.',
            'li': 'https://www.linkedin.com/in/leedavid/',
            'name': 'David Lee',
            'role': 'Principal AI Product Manager, SAP'},
  'links': [('Spotify', 'https://open.spotify.com/episode/1tIOrcwR2n2hVKZ7k7HNw4'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000665956526'),
            ('YouTube', 'https://www.youtube.com/watch?v=F_f0BbRecZk')],
  'paras': ['David talks about high-context vs. low-context cultures, tips for UX/UI designers, his '
            'early entrepreneurial story, and more.'],
  'slug': 'startups-with-seoul-ep-10-david-lee',
  'title': 'Ep 10: David Lee',
  'yt': 'F_f0BbRecZk'},
 {'guest': {'bio': 'Also founded DoctorBase, acquired by Tebra, and JetBridge AI Engineering.',
            'li': 'https://www.linkedin.com/in/johnsungkim/',
            'name': 'John Sung Kim',
            'role': 'Founder &amp; CEO, Five9'},
  'links': [('Spotify', 'https://open.spotify.com/episode/7dIqKO5n6LVOEr0aOkhqY2'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000666734587'),
            ('YouTube', 'https://www.youtube.com/watch?v=2iHyEyy-Wwo')],
  'paras': ['John talks about the early days of his startup journey and some of the mistakes he made, '
            'his recent success, and what he&#8217;s up to now.'],
  'slug': 'startups-with-seoul-ep-11-john-sung-kim',
  'title': 'Ep 11: John Sung Kim',
  'yt': '2iHyEyy-Wwo'},
 {'guest': {'bio': 'A data scientist turned investor; previously made strategic investments at Samsung '
                   'Ventures.',
            'li': 'https://www.linkedin.com/in/sangmin-david-lim-36374348/',
            'name': 'David Sangmin Lim',
            'role': 'Investment Director, Atinum Investment'},
  'links': [('Spotify', 'https://open.spotify.com/episode/10cJZLdi7WC1ShR1WWG1NH'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000668081210'),
            ('YouTube', 'https://www.youtube.com/watch?v=YOr0qNrF208')],
  'paras': ['David Lim, Director at Atinum Investment, Chang Kim, and Aviram Jenik talk about what '
            'Korean startups need to do to be successful in the global market.'],
  'slug': 'startups-with-seoul-ep-12-david-sangmin-lim',
  'title': 'Ep 12: David Sangmin Lim',
  'yt': 'YOr0qNrF208'},
 {'guest': {'bio': 'Built Blind&#8217;s U.S. business from scratch; earlier at TMon.',
            'li': 'https://www.linkedin.com/in/kyumkim/',
            'name': 'Kyum Kim',
            'role': 'Co-Founder, Blind'},
  'links': [('Spotify', 'https://open.spotify.com/episode/3BZPZjWyhiXHJjrIRZivI6'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000668932441'),
            ('YouTube', 'https://www.youtube.com/watch?v=_FywfjLziEI')],
  'paras': ['Kyum talks about his experience at TMon and Blind, where he built a U.S. business from '
            'scratch.'],
  'slug': 'startups-with-seoul-ep-13-kyum-kim',
  'title': 'Ep 13: Kyum Kim',
  'yt': '_FywfjLziEI'},
 {'guest': {'bio': 'Left a large company to start YesPlz AI.',
            'li': 'https://www.linkedin.com/in/jiwonhong/',
            'name': 'Jiwon Hong',
            'role': 'CEO &amp; Co-Founder, YesPlz AI'},
  'links': [('Spotify', 'https://open.spotify.com/episode/3NIs7WnbTXV4uqn7ZedtiN'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000662864132'),
            ('YouTube', 'https://www.youtube.com/watch?v=1UVv6-RePE4')],
  'paras': ['Jiwon shares her journey from a big company to her own startup, sales techniques, and '
            'life-hack tips.'],
  'slug': 'startups-with-seoul-ep-7',
  'title': 'Ep 7: Jiwon Hong of YesPlz AI',
  'yt': '1UVv6-RePE4'},
 {'guest': {'bio': 'Career spans an endowment fund, a venture capital firm, and M&amp;A at a tech '
                   'company.',
            'li': 'https://www.linkedin.com/in/cheolyoung/',
            'name': 'CY Choi',
            'role': 'Independent Director, Hanyang Digitech'},
  'links': [('Spotify', 'https://open.spotify.com/episode/2u23ufCHWw5pWDbsmMv5BA'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000664435018'),
            ('YouTube', 'https://www.youtube.com/watch?v=R3vO6kcDfz0')],
  'paras': ['CY talks about his career spanning an endowment fund, a venture capital firm, and a tech '
            'company where he oversaw M&amp;A.'],
  'slug': 'startups-with-seoul-ep-8-cy-choi',
  'title': 'Ep 8: CY Choi',
  'yt': 'R3vO6kcDfz0'},
 {'guest': {'bio': 'Three-time founder; co-founded Uiflow (YC W21), acquired by Workday.',
            'li': 'https://www.linkedin.com/in/soleun/',
            'name': 'Daniel (Sol) Eun',
            'role': 'Founder &amp; CEO, Vertical Bar'},
  'links': [('Spotify', 'https://open.spotify.com/episode/1BN9AeSGU5wm13L65YRMTQ'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000665100542'),
            ('YouTube', 'https://www.youtube.com/watch?v=40j9JJ-cxBU')],
  'paras': ['Sol shares his experience of starting and selling his own startup, and his take on how '
            'more Korean startups can succeed in the U.S. market.'],
  'slug': 'startups-with-seoul-ep-9-sol-eun',
  'title': 'Ep 9: Sol Eun',
  'yt': '40j9JJ-cxBU'},
 {'guest': {'bio': 'Co-founded Patlytics; previously a Partner at Tribe Capital.',
            'li': 'https://www.linkedin.com/in/paul-lee-in/',
            'name': 'Paul Lee',
            'role': 'CEO &amp; Co-Founder, Patlytics'},
  'links': [('Spotify', 'https://open.spotify.com/episode/66YCgH3Xel9a18Ra2wn8zQ'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000648408045'),
            ('YouTube', 'https://www.youtube.com/watch?v=ndZm-4TSYtA')],
  'paras': ['In this inaugural episode, we invited Paul Lee, Partner at Tribe Capital.'],
  'slug': 'startups-with-seoul-episode-1',
  'title': 'Ep 1: Paul Lee of Tribe Capital',
  'yt': 'ndZm-4TSYtA'},
 {'guest': {'bio': 'Co-founded Relate.',
            'li': 'https://www.linkedin.com/in/chaec/',
            'name': 'Chris Chae',
            'role': 'Head of Marketing, MarqVision'},
  'links': [('Spotify', 'https://open.spotify.com/episode/0ZIXNU5xxhIGcLCzBgAZYV'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000648408122'),
            ('YouTube', 'https://www.youtube.com/watch?v=0_jM-wJ_ETE')],
  'paras': ['In this second episode, we chatted with Chris Chae, co-founder at Relate.'],
  'slug': 'startups-with-seoul-episode-2',
  'title': 'Ep 2: Chris Chae of Relate CRM',
  'yt': '0_jM-wJ_ETE'},
 {'guest': {'bio': 'Builds JIGO, a co-pilot for agreement analysis; previously co-founded Kurvv, '
                   'acquired by AIZEN.',
            'li': 'https://www.linkedin.com/in/ryanshlee/',
            'name': 'Ryan Lee',
            'role': 'Founder &amp; CEO, JIGO'},
  'links': [('Spotify', 'https://open.spotify.com/episode/4qXIkPaNxyHCXkpsOVc1Rd'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000648408265'),
            ('YouTube', 'https://www.youtube.com/watch?v=ts0Su6XixcM')],
  'paras': ['In this third episode, we spoke with Ryan Lee, founder/CEO of JIGO.'],
  'slug': 'startups-with-seoul-episode-3',
  'title': 'Ep 3: Ryan Lee of JIGO',
  'yt': 'ts0Su6XixcM'},
 {'guest': {'bio': 'Built Smore, an interactive survey builder for customer feedback; born in Seoul, '
                   'raised in Sydney.',
            'li': 'https://www.linkedin.com/in/rhaun-hong/',
            'name': 'Clara Hong',
            'role': 'CEO &amp; Co-Founder, Smore'},
  'links': [('Spotify', 'https://open.spotify.com/episode/4CSVpGYCresXjKqaTCfBjO'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000648408123'),
            ('YouTube', 'https://www.youtube.com/watch?v=zH9YjO90IBc')],
  'paras': ['In this episode, we spoke with Clara Hong of Smore.'],
  'slug': 'startups-with-seoul-episode-4',
  'title': 'Ep 5: Clara Hong of Smore',
  'yt': 'zH9YjO90IBc'},
 {'guest': {'bio': 'Invests across the U.S. and Vietnam at Ethos Fund.',
            'li': 'https://www.linkedin.com/in/thedavidyi/',
            'name': 'David Yi',
            'role': 'Managing Partner, Ethos Fund'},
  'links': [('Spotify', 'https://open.spotify.com/episode/1afX04UjUxoZqNrqhwfCEg'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000648408177'),
            ('YouTube', 'https://www.youtube.com/watch?v=F3UGY1WxJRU')],
  'paras': ['We spoke with David Yi of Ethos Fund!'],
  'slug': 'startups-with-seoul-episode-4-2',
  'title': 'Ep 4: David Yi of Ethos Fund',
  'yt': 'F3UGY1WxJRU'},
 {'guest': {'bio': 'Startup founder turned investor.',
            'li': 'https://www.linkedin.com/in/ibreakshit/',
            'name': 'Jiho Kang',
            'role': 'Partner, Korea, Antler'},
  'links': [('Spotify', 'https://open.spotify.com/episode/1c6rZPLsMkXPnkqPwdJceG'),
            ('Apple Podcasts',
             'https://podcasts.apple.com/us/podcast/startups-with-seoul/id1734893626?i=1000662151733'),
            ('YouTube', 'https://www.youtube.com/watch?v=yDT8e9lFC4Y')],
  'paras': ['Jiho&#8217;s journey from a startup entrepreneur to a successful VC; tips for Korean '
            'startups based on Jiho&#8217;s observation of different Antler programs in different '
            'countries.'],
  'slug': 'startups-with-seoul-episode-6',
  'title': 'Ep 6: Jiho Kang of Antler Korea',
  'yt': 'yDT8e9lFC4Y'}]
